export interface Episodes {
    name: string;
    id: string;
    date: string;
    description: string;
}

export interface AxiosUpcoming {
    upcoming: Episode[];
    ongoing: Episode[];
}

export interface Episode {
    title: string;
    when: string;
    img: string;
    alternative: string;
    slug: string;
}

export interface AxiosRecent {
    date: string;
    anime: string;
    description: string;
    hot: boolean;
    episode: string;
    img: string;
    id: string;
    slug: string;
}

export interface AxiosAnime {
    episodes: Episodes[];
    img: string;
    title: string;
    rating: string;
    score: string;
    alternative: string;
    genres: string[];
    description: string;
    next: string;
    year: string;
    status: string;
    relations: {
        sequel: Relation | null;
        prequel: Relation | null;
    };
}

export interface Relation {
    title: string;
    slug: string;
    img: string;
}

export interface AxiosSearch {
    title: string;
    slug: string;
    year: string;
    img: string;
    alternative: string;
}

// Generated by https://quicktype.io

export interface AxiosVideos {
    source: Source[];
    source_bk: Source[];
    track: any[];
    advertising: any[];
    linkiframe: string;
}

export interface AxiosEpisode {
    videos: AxiosVideos;
    ep: number;
}

export interface Source {
    file: string;
    label: string;
    type: string;
    default?: string;
}
