// Generated by https://quicktype.io

export interface AxiosRecentlySub {
    title: string;
    latest_ep: string;
    url: string;
    thumbnail: string;
}

// Generated by https://quicktype.io

export interface AxiosEpisodeAnime {
    vidstreaming: string;
    vidcdn: string;
    streamsb: string;
    doodstream: string;
    fembed: string;
}

// Generated by https://quicktype.io

export interface ApiEpisodeAnime {
    source: Source[];
    source_bk: Source[];
    track: any[];
    advertising: any[];
    linkiframe: string;
}

export interface Source {
    file: string;
    label: string;
    type: string;
    default?: string;
}

// Generated by https://quicktype.io

export interface ApiRecently {
    title: string;
    latest_ep: string;
    url: string;
    thumbnail: string;
}

export interface PageProps {
    fallback: any;
    error?: {
        status: string;
        data: string;
    };
}

// Generated by https://quicktype.io

export interface APIAnime {
    animetitle?: string;
    thumbnail?: string;
    alternate_titles?: string;
    anime_status?: string;
    anime_genre?: string;
    anime_year?: string;
    total_episodes?: string;
    anime_summary?: string;
}

// Generated by https://quicktype.io

export interface APISearch {
    animetitle: string;
    url: string;
    thumbnail: string;
}
